### ISSUE TITLE
Ctrl/Shift/v Not working on Ubuntu 10.04

### ISSUE THREAD

**Issue by aplatypus** [denco/vscode-confluence-markup#12]
Control/Shift/V is the keyboard combo for the X-Windows past buffer.  This combination doesn't work with Ubuntu Linux.

**Comment by aplatypus** [comment]
Ubuntu 18.10; Cinnamon v 3.8.8

Please refer to the problem description.  Ctrl+Shift+V is an X-Windows command.  desktops run _within_ and at the behest of the X.Org layer.  And I guess for the future Mir and Wayland.

**Comment by denco** [comment]
@aplatypus FYI: Issue will be closed tomorrow.
