### ISSUE TITLE
Two or more monospace-formatted words in a line will not render properly

### ISSUE THREAD

**Issue by macintacos** [denco/vscode-confluence-markup#17]
The following doesn't render properly in the confluence preview:

```
This is a {{test}} of how things work with {{confluence}} markup.
```

It looks something like:

![](https://cl.ly/60811d16b3d2/Image%202019-08-08%20at%2018.18.20.png)

**Comment by denco** [comment]
@macintacos 
Hi, thanks for providing issue, try to fix it soon.
