### ISSUE TITLE
Convert from Markdown

### ISSUE THREAD

**Issue by TamasBarta** [denco/vscode-confluence-markup#19]
Hi!
I long searched for a solution in VSCode to edit Confluence stuff, so thank you very much for that. One thing that would be very useful, is the ability to convert Markdown files to Confluence, since Markdown is much better, and I use that to write documents, and then just upload that to Confluence (we have no Markdown plugin AFAIK).
What do you think?

**Comment by denco** [comment]
Hi, 

actually i'm not plan smth. in this way.  

My motivation for this plugin to write a files with Confluence/Jira syntax and have possibility to preview it locally without connection to Confluence/Jira.

Markdown is pretty simple, it's true. But it's has a lot of limitations. IMHO it's comparable to Confluence Markup, which is not perfect too... ;)

If you want to convert a markdown to confluence.  It's exist one plugin for vscode: [Markdown to JIRA](https://marketplace.visualstudio.com/items?itemName=chintans98.markdown-jira) it could be helpful for U.

Thx and Greez,
Denis

**Comment by TamasBarta** [comment]
Hi,
thanks for the explanation and the plugin recommendation. I think I'll be fine with this route. I just couldn't find that other extension before.
BR, Tamás
