### ISSUE TITLE
Can not launch Previewer on Mac OS

### ISSUE THREAD

**Issue by felixbecker** [denco/vscode-confluence-markup#20]
Hi, 
I installed the plugin in vscode (Version: 1.40.0) on MacOS Mojave.
Created a *.confluence file and hit `cmd+shift+v` and was prompted with an error: `command 'markdown.extension.togglePreview' not found` 

Has anyone experienced the same? What can I do to fix it?

**Comment by denco** [comment]
Hi.

Can't test it in a right way, didn't have mac. I've try it with virtualized MacOS Catalina and vscode 1.40.0, plugin version 0.1.7.

I can see a both preview types, on other panel and on the same. 

Can U try Preview without using keyboard shortcuts? 

- Possibility 1:
In the right top corner of Editor U should see `...` -Menu with more actions. In Catalina I can choose: `Open Preview` or `Open Preview to the Side`,
- Possibility 2:
Is Over: Command Palette: `cmd+P`, or `View` -> `Command Palette`, than if U type: `confluence` U should see both options to preview.

Can U see a preview with one of possibilities above or did U get the same error?

Thx!

**Comment by felixbecker** [comment]
Hi,
thanks for your quick feedback. Both possibilities work fine. It looks like the keyboard shortcut does not work for me. Maybe it is cause by a collision of other plugins. Do you have any information how to configure this correctly?

**Comment by denco** [comment]
Hi,
You are welcome, hm, probably it's something with Key Shortcuts "overwrite".

I would rebind a involved key shortcuts. 

Please see: [Key Bindings for Visual Studio Code](https://code.visualstudio.com/docs/getstarted/keybindings)
or [default keyboard shortcuts on macos](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf)

If it solve's your problem it would be great if U close the issue.

Thx!

**Comment by felixbecker** [comment]
Thank you ... will check out my bindings and previewing manually works just fine. I'll close the issue.
