### ISSUE TITLE
panel support

### ISSUE THREAD

**Issue by tarterp** [denco/vscode-confluence-markup#22]
panels as described at [Jira's Text Formatting](https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=advanced)

**Comment by denco** [comment]
Hi,
sorry for later responce, will check the possibility.

Simple container, without formatting, could be a easier to implement, it's ok for U or did U need a extended parameters like Title and Colors?

Greez!

**Comment by YoriMoura** [comment]
Hi,

I think a simple container, to begin with, would be great! But with extended parameters would be awesome! :D 

Btw, **awesome work!**

**Comment by denco** [comment]
Thx, for the info, will add simple panel support soon!

**Comment by denco** [comment]
please check release [0.1.9](https://github.com/denco/vscode-confluence-markup/releases/tag/0.1.9)

**Comment by denco** [comment]
U R welcome! :wink:
