### ISSUE TITLE
Support to {color:}

### ISSUE THREAD

**Issue by YoriMoura** [denco/vscode-confluence-markup#32]
Hello! 😁   
It would be great if this extension was able to translate the {color} tag in the preview. 😄 

Keep up with the awesome work!

**Comment by denco** [comment]
Hi,

color macro is supported, but actually with 'word' colors...

this, should work: `{color:cyan}cyan{color}`

smth like: `{color:rgb(12,200,112)}rgb(12,200,112){color}` or `{color:#12FFFE}hex#12FFFE(color}` could work, but it's not testet.

will check what i can do.
