### ISSUE TITLE
Monospaced Text does not seem to be supported

### ISSUE THREAD

**Issue by muman613** [denco/vscode-confluence-markup#34]
First thank you for providing this plug-in. I just found it and think it is a very useful plug-in. I have been using it to create tables which will be cut/pasted into Jira (which uses Confluence Markdown).

I believe that the monospace text formatting `{{text}}` does not appear in the preview as monospace text.

We use monospace text in tables to identify register names and addresses for the hardware we are working with. It would be nice if this plugin rendered the text properly.

**Comment by muman613** [comment]
![image](https://user-images.githubusercontent.com/2244649/114205477-2e94e080-990f-11eb-8eb1-fdcdb2de1131.png)

**Comment by muman613** [comment]
Ok, monospace text works for text but not numbers....

![image](https://user-images.githubusercontent.com/2244649/114206133-e4602f00-990f-11eb-9afd-fdfb8c4017c9.png)

**Comment by denco** [comment]
Hi, 

Thx for the issue description! I can approve that `monospace` regex contains some errors.

U R welcome to use confluence preview plugin ;)

Will fix this soon.

Other point, as I see underscore rendering (in table header) doesn't work properly too.

Greez.
