### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by etienne-monier** [denco/vscode-confluence-markup#39]
Hi,

I'm using this very nice pluggin for 2 weeks and I find it wonderful.

Yet, I may miss something, the images are not rendered.

I use the following macro `!/path/to/picture.png|width=500!` but it only show a small image icon.

Can you tell me if this feature exists?

Thanks for your help.

**Comment by etienne-monier** [comment]
Thanks a lot!
It solves image rending using relative as absolute path name.

That's just a suggestion, but this would be awesome to add a kind of local image path definition.

Just to explain. I use the pluggin to write confluence markup before sending it to a Confluence server which is not always available. On this server, I  need to upload images for a specific page, so I call them directly with `img.png` where I use `img_dir/img.png` on my local computer. Using a command to setup the image path at the beginning of the file would be great, but I think this would be too complicated and not confluence-friendly.

Whatever, thanks for the fix :)

**Comment by denco** [comment]
Hi,

probably it can be implemented, will check it.

As workaround/suggestion try to put image file direct into directory with your confluence/Jira file. In this way it should be possible to use only file name with extension, without file path.

Directory will be a bit messy, but it should be confirm with your confluence/Jira setup.

Let me know if it's works.

U R Welcome!

Greez.

**Comment by etienne-monier** [comment]
That's what I did. By putting the pictures with the src file, I get the desired result. Putting them to another directory is just for convenience.
Thanks!
