### ISSUE TITLE
The info, tip, note, and warning macros are not rendered

### ISSUE THREAD

**Issue by etienne-monier** [denco/vscode-confluence-markup#41]
Hi,

I found another problem in your wonderful rending tool. That's the info, tip, note, and warning macros which are not rendered.

Have a look at [this page](https://confluence.atlassian.com/doc/info-tip-note-and-warning-macros-51872369.html).

A minimal code:
```
{info:title=This is my title|icon=false}
This is _important_ information.
{info}
```

Thanks for your help!

**Comment by denco** [comment]
Hi, sorry I'm bit busy now but will implement the features in next time.

**Comment by vfontes-atlassian** [comment]
+1 having this feature working would be super nice!

PS: this extension _may or may not_ be used inside Atlassian ;)
