### ISSUE TITLE
Great ext giving speed of creation, but ....

### ISSUE THREAD

**Issue by macasas** [denco/vscode-confluence-markup#43]
Hi, just installed your extension and love how fast I can create documents and see what I am doing.

But after all this quick creation, how do I connect it to my Confluence pages and upload the files, from within VS Code?

If I need to then copy and paste, I will end up just editing it in Confluence so I maintain changes only in one place.  Copy and Paste from the VSC editor and takes with it line numbers and background colouring.

I've tried looking for the Confl. webDAV plugin, but it appears no longer available. Rest API seems overkill and I'm not sure how that would connect from within the VSC editor.

I'm hoping you have a solution to this issue, because if I could like my VSC project to my Confluence and then "push" like a git thing that would be awesome.  

Many thanks.

**Comment by denco** [comment]
@macasas will close this, issue, cause actually will be not implemented.
