### ISSUE TITLE
Not rendering variations of bulleted list correctly

### ISSUE THREAD

**Issue by alecxvs** [denco/vscode-confluence-markup#44]
Lists like
```
- abc
-- abcdef
```
render correctly but Jira at least can format these differently. They are often preceded by whitespace in the WYSIWYG editor, which does not render with any bullets in the preview:
```
- abc
  -- abcdef
```
and mixed numeric and bullet lists don't work either:
```
# abc
# def
  #* foo
    #** bar
```
(above example is based on the confluence markup doc, but i also use the following format in Jira:)
```
# abc
# def
  ** foo
    *** bar
```

nested bullet lists also don't seem to show the hollow bullet for the second level as expected

**Comment by denco** [comment]
Hi thanks for providing issue, will check it. @alecxvs it'possible to provide some renderings/screenshots, how it looks in Confluence/Jira it would be awesome!

Thx in advance.
