### ISSUE TITLE
Not all emojis are supported

### ISSUE THREAD

**Issue by bedesv** [denco/vscode-confluence-markup#54]
I regularly use a few of the Jira emojis in my comments, but not all of them are supported by this extension.
 
Supported Emojis:
`:) :( :P :D ;) (y) (n) (i) (/) (x) (!)`
![image](https://github.com/denco/vscode-confluence-markup/assets/5328041/25ef7714-b00b-499b-a6e6-9c9144c813bc)

Unsupported Emojis:
`(+) (-) (?) (on) (off) (*) (*r) (*g) (*b) (*y) (flagoff) (flagon)`
![image](https://github.com/denco/vscode-confluence-markup/assets/5328041/6f235791-c772-4bb4-8093-a25401d808ad)

You can see that the `*` characters are interpreted as bold by the extension.

Here's a screenshot of what the emojis look like on Jira:
![image](https://github.com/denco/vscode-confluence-markup/assets/5328041/969fa497-e569-4c42-b00f-489323444f2d)

**Comment by denco** [comment]
Hi @bedesv will check it, should be simple. Thx!
