### ISSUE TITLE
Preview doesn't display indented list

### ISSUE THREAD

**Issue by BattleBas** [denco/vscode-confluence-markup#7]
When using the syntax ** to indent a list, the preview window (ctrl+shit+v) doesn't display the line as indented.

**Example of Confluence Markup** 
![image](https://user-images.githubusercontent.com/3441183/38689148-6b815d66-3e40-11e8-9a15-522a669e0ae4.png)

**Example of what preview shows**
![image](https://user-images.githubusercontent.com/3441183/38689231-a9f6c5e0-3e40-11e8-8ac2-cf61e6600365.png)

Thank you!

**Comment by denco** [comment]
Yes, nested or sub lists are not supported in 1.2

I've try to fix it, would you like to test fixed version? 

(unzip and install over extensions (...) install from vsix file)

Please check attached file:
[confluence-markup-0.1.3.vsix.zip](https://github.com/denco/vscode-confluence-markup/files/2020295/confluence-markup-0.1.3.vsix.zip)

**Comment by BattleBas** [comment]
Works for me, great job thank you!

![image](https://user-images.githubusercontent.com/3441183/40387949-c2c4862c-5dd3-11e8-999a-34e467348bb0.png)

**Comment by potchin** [comment]
Is this new version with the fix planned to be released via the marketplace soon?
